# Generated by Django 5.2.7 on 2025-10-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.CharField(max_length=255, verbose_name='Manzil')),
                ('royxatdan_otgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Royxatdan otgan sana')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('transport', models.CharField(max_length=50, verbose_name='Transport turi (masalan, motor, mashina)')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
            },
        ),
        migrations.CreateModel(
            name='Idish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Idish nomi')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('mavjud', models.BooleanField(default=True, verbose_name='Mavjudmi?')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Idish',
                'verbose_name_plural': 'Idishlar',
            },
        ),
        migrations.CreateModel(
            name='Menyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Menyu nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsif')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyular',
            },
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Restoran nomi')),
                ('manzil', models.CharField(max_length=255, verbose_name='Manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('ochilish_vaqti', models.TimeField(verbose_name='Ochiladi')),
                ('yopilish_vaqti', models.TimeField(verbose_name='Yopiladi')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoranlar',
            },
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1, verbose_name='Miqdor')),
                ('umumiy_narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('yetkazilmoqda', 'Yetkazilmoqda'), ('yakunlandi', 'Yakunlandi')], default='yangi', max_length=50, verbose_name='Holat')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to='app.foydalanuvchi', verbose_name='Foydalanuvchi')),
                ('idish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to='app.idish', verbose_name='Idish')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='KoribChiqish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reyting', models.PositiveSmallIntegerField(default=5, verbose_name='Reyting (1-5)')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fikrlar', to='app.foydalanuvchi', verbose_name='Foydalanuvchi')),
                ('idish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fikrlar', to='app.idish', verbose_name='Idish')),
            ],
            options={
                'verbose_name': 'Korib chiqish',
                'verbose_name_plural': 'Korib chiqishlar',
            },
        ),
        migrations.AddField(
            model_name='idish',
            name='menyu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idishlar', to='app.menyu', verbose_name='Menyu'),
        ),
        migrations.AddField(
            model_name='menyu',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menyular', to='app.restoran', verbose_name='Restoran'),
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tolov summasi')),
                ('usul', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('onlayn', 'Onlayn')], max_length=50, verbose_name='Tolov usuli')),
                ('tolangan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Tolov sanasi')),
                ('buyurtma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tolov', to='app.buyurtma', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Tolov',
                'verbose_name_plural': 'Tolovlar',
            },
        ),
        migrations.CreateModel(
            name='YetkazibBerish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=255, verbose_name='Yetkazib berish manzili')),
                ('yetkazilgan_vaqt', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('buyurtma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yetkazish', to='app.buyurtma', verbose_name='Buyurtma')),
                ('haydovchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yetkazilgan_buyurtmalar', to='app.haydovchi', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
            },
        ),
    ]
