# Generated by Django 5.2.7 on 2025-10-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Bo'lim haqida ma’lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mahsulot tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('year', models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan yil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami narx')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('shipped', 'Yetkazilmoqda'), ('delivered', 'Yetkazilgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.customer', verbose_name='Buyurtmachi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
