# Generated by Django 5.2.7 on 2025-10-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchi')),
                ('idish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.idish')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foydalanuvchi')),
                ('idish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.idish')),
            ],
        ),
    ]
